### PR TITLE
The New York Times Feature

### PR DESCRIPTION
**Pull request by Bekhzod96**
This is a version of a NYT article in which we use  Flexbox, GRID, and Float tools to manipulate the appearance of a Web page.

- Flexbox on the header and main article, the aside bar, the index list and the Footer links.

- Float is used on sections of the Header,

- Grid is used in the Theories, Astronomy and Editor's Picks sections.

### CODE REVIEW

**Comment by SofiBretz** [comment]
Code under review by SofiBretz. Thanks!✨

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

- [ ] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

- [ ] Consider adding the image smaller as the original page, the text size on the image description has to be bigger as the original page. 



- [ ] Consider adding the description below the video. You are missing text here, please follow the text as the original page before continuing with the ' Spirals in the Sky' paragraph.





- [ ] The image and the description of the image must be wider than the text as the original page.





Consider the color of the links has to have a similar color to the original page.





[OPTIONAL]

- [ ] Consider adding a screenshot of your project and the demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Just one more thing left:
* [ ] Stickler error should be fixed.

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
